### ISSUE TITLE
error in starting the server

### ISSUE THREAD

**Issue by Kamayani-Goswami** [udacity/cloud-developer#166]
When I'm writing the command 'npm run dev' ,it is showing error and I'm unable to start the server.

C:\Users\GENIUS>npm run dev

> udacity-c2-basic-server@1.0.0 dev C:\Users\GENIUS
> ts-node-dev --respawn --transpileOnly ./src/server.ts

Using ts-node version 8.10.1, typescript version 3.8.3
(node:11848) UnhandledPromiseRejectionWarning: TypeError: express_1.default is not a function
    at C:\Users\GENIUS\src\server.ts:10:22
    at step (C:\Users\GENIUS\src\server.ts:33:23)
    at Object.next (C:\Users\GENIUS\src\server.ts:14:53)
    at C:\Users\GENIUS\src\server.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\GENIUS\src\server.ts:4:12)
    at C:\Users\GENIUS\src\server.ts:6:2
    at Object.<anonymous> (C:\Users\GENIUS\src\server.ts:86:3)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module._compile (C:\Users\GENIUS\node_modules\source-map-support\source-map-support.js:547:25)
(node:11848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

rl.on line

rl.on line

**Comment by isidrolo80** [comment]
This is a warning only, I had the same message shown when managing hashed data. It was fixed by changing the generateJWT function in the auth.router.ts file to

`function generateJWT(user: User): string {
    //@TODO Use jwt to create a new JWT Payload containing
    return jwt.sign({user}, config.jwt.secret);
}`

**Comment by Berryakin2010** [comment]
I'm having a similar issue.  I've updated the code lines 21 not reading resp to response.  It helped somewhat, but a new issue showing error code "Elifecycle".

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! udacity-c2-basic-server@1.0.0 dev: `ts-node-dev --respawn --transpileOnly ./src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the udacity-c2-basic-server@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by apurva165** [comment]
> I'm having a similar issue. I've updated the code lines 21 not reading resp to response. It helped somewhat, but a new issue showing error code "Elifecycle".
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! udacity-c2-basic-server@1.0.0 dev: `ts-node-dev --respawn --transpileOnly ./src/server.ts`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the udacity-c2-basic-server@1.0.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

i am getting same issue

**Comment by apurva165** [comment]
If you have the newer version of ts-node-dev, you need to update package.json line 8 
from: --transpileOnly 
to:  --transpile-only
this should fix the issue

**Comment by codepolariz** [comment]
i cant start the server.. No error.... i changed my config based on @apurva165 
udacity-c2-restapi@1.0.0 dev C:\..........\..\..\
> ts-node-dev --respawn --transpile-only ./src/server.ts

Using ts-node version 8.3.0, typescript version 3.5.3

**Comment by Berryakin2010** [comment]
> If you have the newer version of ts-node-dev, you need to update package.json line 8
> from: --transpileOnly
> to: --transpile-only
> this should fix the issue

I tried your fix after taking a break from it, and the server still does not work.
